### PR TITLE
Separate HTML attributes from styling props

### PR DESCRIPTION
**Pull request by lttb**
[Online example](https://codesandbox.io/s/5yVZ8D7jR)

As a result of discussions in https://github.com/styled-components/styled-components/issues/439 and https://github.com/styled-components/styled-components/pull/731 let's consider this interface:

```jsx
<Button style={{color, padding: color.length}} />
```

As for me it's very useful and clear. And we can use such things:

```jsx
type Styled<T> = (props: {style?: T}) => React$Element<*>

const Button: Styled<{
  margin: number, 
  color?: 'red' | 'green'
}> = styled('button', {
  margin: ({margin = 0}) => margin,
  color: ({color = 'red'}) => color
})

// ok
<Button style={{margin: 10}} />

// flow type error
<Button style={{margin: 'ten'}} />

// flow type error too
<Button style={{margin: 10, color: 'blue'}} />
```

image

### CODE REVIEW

**Comment by kof** [comment]
Using style property is a bit opinionated because user still probably have a possibility to use inline styles. Though another way to use inline styles would be to just access a class name and build a styled primitive manually.

**Comment by lttb** [comment]
The `look` property instead of `style` is the best solution for me now

**Comment by iamstarkov** [comment]
i have the same concern as @kof and dont understand look thingy. @lttb can you help?

**Comment by iamstarkov** [comment]
though, i love flowtype typings

**Comment by kof** [comment]
On the other hand if one really needs inline styles which is  a bad idea most of the time, one can use base styles and combine classes with inline styles as always. In case of styled primitives, we already expect a primitive to be styled.  If `style` wouldn't mean inline styles for the rest of the world, it would be a quite good fit.

**Comment by lttb** [comment]
@iamstarkov about `style` prop: u can look at this from such side: with  styled-jss u **should not** to use inline styles, this abstraction just fully replace it.

but I suggested another way: use 'look' prop instead

```jsx
<Button look={{color: 'red'}} />
```

**Comment by kof** [comment]
This is a bad example:

```js
<Button look={{color: 'red'}} />
```

This is better:

```js
<Button look={{primary: true}} />
```

And yet, does it feel natural to you compared to this?

```js
<Button primary />
```

**Comment by lttb** [comment]
agreed, but it seems that this is a common usage.
@kof your example I see this way:

```jsx
<Button look="primary" />
```
composition:
```jsx
<Button look={{primary, secondary}} />
```

**Comment by kof** [comment]
I think they all suck compared to just using normal props, like right now. We should try find another solution for the root of the problem in react: avoiding the whitelist. Somehow  a styled primitive should be able to filter the props it knows and not forward them.

**Comment by lttb** [comment]
Close in case of https://github.com/lttb/is-react-prop/pull/3

**Pull request closed without merging**
