### PR TITLE
Fix peerDependencies

### PR DESCRIPTION
**Pull request by lttb**

### CODE REVIEW

**Comment by kof** [comment]
Why older react version and why no react-dom?

**Comment by lttb** [comment]
older because people have warnings with older versions, but we require version just from '15.3.0'. 

react-dom is a peer dependency of is-react-prop, but not of our package

**Comment by kof** [comment]
right, then we might go even older

**Comment by kof** [comment]
if there are no compatibility issues

**Comment by lttb** [comment]
not now because of `PureComponent`: https://github.com/facebook/react/blob/master/CHANGELOG.md#1530-july-29-2016

according to my local checks `PureComponent` was a little bit faster on re-render, but we need to explore this deeper of course

**Pull request merged**
